version: '2'
services:
  registry:
    image: vmware/registry-photon:v2.6.2-v1.4.0
    container_name: registry
    restart: always
    volumes:
      - /mnt/AUengineering/registrystorage:/registry:z
      - ./common/config/registry/:/etc/registry/:z
    networks:
      - harbor
    environment:
      - TZ=EST
      - GODEBUG=netdns=cgo
    command:
      ["serve", "/etc/registry/config.yml"]
    logging:
      driver: "syslog"
      options:
        syslog-address: "tcp://devlogs.aunalytics.com:1514"
        tag: "registry"
  mysql:
    image: vmware/harbor-db:v1.4.0
    container_name: harbor-db
    restart: always
    volumes:
      - /data/database:/var/lib/mysql:z
    networks:
      - harbor
    environment:
      - TZ=EST
    env_file:
      - ./common/config/db/env
    logging:
      driver: "syslog"
      options:
        syslog-address: "tcp://devlogs.aunalytics.com:1514"
        tag: "mysql"
  adminserver:
    image: vmware/harbor-adminserver:v1.4.0
    container_name: harbor-adminserver
    environment:
      - TZ=EST
    env_file:
      - ./common/config/adminserver/env
    restart: always
    volumes:
      - /data/config/:/etc/adminserver/config/:z
      - /data/secretkey:/etc/adminserver/key:z
      - /data/:/data/:z
    networks:
      - harbor
    logging:
      driver: "syslog"
      options:
        syslog-address: "tcp://devlogs.aunalytics.com:1514"
        tag: "adminserver"
  ui:
    image: vmware/harbor-ui:v1.4.0
    container_name: harbor-ui
    environment:
      - TZ=EST
    env_file:
      - ./common/config/ui/env
    restart: always
    volumes:
      - ./common/config/ui/app.conf:/etc/ui/app.conf:z
      - ./common/config/ui/private_key.pem:/etc/ui/private_key.pem:z
      - ./common/config/ui/certificates/:/etc/ui/certificates/:z
      - /data/secretkey:/etc/ui/key:z
      - /data/ca_download/:/etc/ui/ca/:z
      - /data/psc/:/etc/ui/token/:z
    networks:
      - harbor
    depends_on:
      - adminserver
      - registry
    logging:
      driver: "syslog"
      options:
        syslog-address: "tcp://devlogs.aunalytics.com:1514"
        tag: "ui"
  jobservice:
    image: vmware/harbor-jobservice:v1.4.0
    container_name: harbor-jobservice
    environment:
      - TZ=EST
    env_file:
      - ./common/config/jobservice/env
    restart: always
    volumes:
      - /data/job_logs:/var/log/jobs:z
      - ./common/config/jobservice/app.conf:/etc/jobservice/app.conf:z
      - /data/secretkey:/etc/jobservice/key:z
    networks:
      - harbor
    depends_on:
      - ui
      - adminserver
    logging:
      driver: "syslog"
      options:
        syslog-address: "tcp://devlogs.aunalytics.com:1514"
        tag: "jobservice"
  proxy:
    image: vmware/nginx-photon:v1.4.0
    container_name: nginx
    environment:
      - TZ=EST
    restart: always
    volumes:
      - ./common/config/nginx:/etc/nginx:z
    networks:
      - harbor
    ports:
      - 80:80
      - 443:443
      - 4443:4443
      - 5000:5000
    depends_on:
      - mysql
      - registry
      - ui
    logging:
      driver: "syslog"
      options:
        syslog-address: "tcp://devlogs.aunalytics.com:1514"
        tag: "proxy"
networks:
  harbor:
    external: false
