version: '2'
services:
  ui:
    networks:
      harbor-clair:
        aliases:
          - harbor-ui
    environment:
      - TZ=EST
  jobservice:
    networks:
      - harbor-clair
  registry:
    networks:
      - harbor-clair
  postgres:
    networks:
      harbor-clair:
        aliases:
          - postgres
    container_name: clair-db
    image: vmware/postgresql-photon:v1.4.0
    restart: always
    environment:
      - TZ=EST
    env_file:
      ./common/config/clair/postgres_env
    volumes:
      - ./common/config/clair/postgresql-init.d/:/docker-entrypoint-initdb.d:z
      - /data/clair-db:/var/lib/postgresql/data:z
    logging:
      driver: "syslog"
      options:
        syslog-address: "tcp://devlogs.aunalytics.com:1514"
        tag: "clair-db"
  clair:
    networks:
      - harbor-clair
    container_name: clair
    image: vmware/clair-photon:v2.0.1-v1.4.0
    restart: always
    environment:
      - TZ=EST
    cpu_quota: 150000
    depends_on:
      - postgres
    volumes:
      - ./common/config/clair:/config:z
    logging:
      driver: "syslog"
      options:
        syslog-address: "tcp://devlogs.aunalytics.com:1514"
        tag: "clair"
networks:
  harbor-clair:
    external: false
